"""schema complet en francais

Revision ID: 08d3179755b9
Revises: 
Create Date: 2026-09-18 10:04:22.762528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08d3179755b9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('utilisateurs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('mot_de_passe_hache', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('CANDIDAT', 'RECRUTEUR', 'ADMINISTRATEUR', name='userrole'), nullable=False),
    sa.Column('persona', sa.Enum('PME', 'ENTREPRENEUR', 'RESPONSABLE_RH', 'RECRUTEUR', 'GESTIONNAIRE_SANS_RH', name='recruteurpersona'), nullable=True),
    sa.Column('est_actif', sa.Boolean(), nullable=False),
    sa.Column('email_verifie', sa.Boolean(), nullable=False),
    sa.Column('consentement_donne_le', sa.DateTime(), nullable=True),
    sa.Column('version_politique_consentement', sa.String(length=20), nullable=True),
    sa.Column('cree_le', sa.DateTime(), nullable=False),
    sa.Column('modifie_le', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_utilisateurs_email'), 'utilisateurs', ['email'], unique=True)
    op.create_table('jetons_reinitialisation_mot_de_passe',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('utilisateur_id', sa.Uuid(), nullable=False),
    sa.Column('jeton', sa.String(length=255), nullable=False),
    sa.Column('expire_le', sa.DateTime(), nullable=False),
    sa.Column('utilise', sa.Boolean(), nullable=False),
    sa.Column('cree_le', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jetons_reinitialisation_mot_de_passe_jeton'), 'jetons_reinitialisation_mot_de_passe', ['jeton'], unique=True)
    op.create_table('journaux_email',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('utilisateur_id', sa.Uuid(), nullable=False),
    sa.Column('type_email', sa.String(length=100), nullable=False),
    sa.Column('statut', sa.Enum('ENVOYE', 'ECHEC', 'REPRIS', name='emailstatus'), nullable=False),
    sa.Column('desabonne_le', sa.DateTime(), nullable=True),
    sa.Column('envoye_le', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('utilisateur_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('NOUVELLE_RECOMMANDATION', 'CANDIDATURE_RECUE', 'CHANGEMENT_ETAPE', 'ENTREVUE_PROPOSEE', 'CANDIDATURE_REFUSEE', name='notificationtype'), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('lu', sa.Boolean(), nullable=False),
    sa.Column('cree_le', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('postes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('recruteur_id', sa.Uuid(), nullable=False),
    sa.Column('titre', sa.String(length=255), nullable=True),
    sa.Column('description_brute', sa.Text(), nullable=True),
    sa.Column('description_generee', sa.Text(), nullable=True),
    sa.Column('statut', sa.Enum('BROUILLON', 'PUBLIEE', 'DEPUBLIEE', name='jobstatus'), nullable=False),
    sa.Column('mode_creation', sa.Enum('CHAT', 'FORMULAIRE', name='jobcreationmode'), nullable=False),
    sa.Column('jeton_lien_candidature', sa.String(length=64), nullable=False),
    sa.Column('publie_le', sa.DateTime(), nullable=True),
    sa.Column('cree_le', sa.DateTime(), nullable=False),
    sa.Column('modifie_le', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['recruteur_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_postes_jeton_lien_candidature'), 'postes', ['jeton_lien_candidature'], unique=True)
    op.create_table('preferences_notification',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('utilisateur_id', sa.Uuid(), nullable=False),
    sa.Column('notifier_nouvelle_recommandation', sa.Boolean(), nullable=False),
    sa.Column('notifier_candidature_recue', sa.Boolean(), nullable=False),
    sa.Column('notifier_changement_etape', sa.Boolean(), nullable=False),
    sa.Column('notifier_entrevue_proposee', sa.Boolean(), nullable=False),
    sa.Column('notifier_candidature_refusee', sa.Boolean(), nullable=False),
    sa.Column('notifier_recapitulatif_hebdo', sa.Boolean(), nullable=False),
    sa.Column('notifier_rappel_profil', sa.Boolean(), nullable=False),
    sa.Column('modifie_le', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('utilisateur_id')
    )
    op.create_table('profils_candidats',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('utilisateur_id', sa.Uuid(), nullable=False),
    sa.Column('localisation', sa.String(length=255), nullable=True),
    sa.Column('type_poste_recherche', sa.String(length=255), nullable=True),
    sa.Column('taux_completude', sa.Integer(), nullable=False),
    sa.Column('consentement_banque_profils_le', sa.DateTime(), nullable=True),
    sa.Column('cree_le', sa.DateTime(), nullable=False),
    sa.Column('modifie_le', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('utilisateur_id')
    )
    op.create_table('candidatures',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('poste_id', sa.Uuid(), nullable=False),
    sa.Column('profil_candidat_id', sa.Uuid(), nullable=False),
    sa.Column('etape_actuelle', sa.Enum('CANDIDATURE', 'SHORTLIST', 'ENTREVUE', 'DECISION', name='pipelinestage'), nullable=False),
    sa.Column('postule_le', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['poste_id'], ['postes.id'], ),
    sa.ForeignKeyConstraint(['profil_candidat_id'], ['profils_candidats.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('competences_candidat',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('profil_candidat_id', sa.Uuid(), nullable=False),
    sa.Column('type_competence', sa.Enum('COMPETENCE', 'LANGUE', 'DOMAINE_EXPERIENCE', 'TYPE_POSTE_COMPATIBLE', name='skilltype'), nullable=False),
    sa.Column('valeur', sa.String(length=255), nullable=False),
    sa.Column('source', sa.Enum('EXTRAIT', 'CORRIGE', name='skillsource'), nullable=False),
    sa.Column('cree_le', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['profil_candidat_id'], ['profils_candidats.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('criteres_poste',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('poste_id', sa.Uuid(), nullable=False),
    sa.Column('type_critere', sa.Enum('INTITULE', 'LIEU', 'LANGUE', 'EXPERIENCE', 'COMPETENCE', name='criteriontype'), nullable=False),
    sa.Column('valeur', sa.String(length=255), nullable=False),
    sa.Column('niveau', sa.Enum('OBLIGATOIRE', 'IMPORTANT', 'SOUHAITABLE', name='criterionlevel'), nullable=False),
    sa.Column('cree_le', sa.DateTime(), nullable=False),
    sa.Column('modifie_le', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['poste_id'], ['postes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cvs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('profil_candidat_id', sa.Uuid(), nullable=False),
    sa.Column('chemin_fichier', sa.String(length=500), nullable=False),
    sa.Column('type_fichier', sa.String(length=10), nullable=False),
    sa.Column('statut_analyse', sa.Enum('EN_ATTENTE', 'TRAITE', 'ECHEC', name='cvanalysisstatus'), nullable=False),
    sa.Column('est_actuel', sa.Boolean(), nullable=False),
    sa.Column('depose_le', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['profil_candidat_id'], ['profils_candidats.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entrees_shortlist',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('poste_id', sa.Uuid(), nullable=False),
    sa.Column('profil_candidat_id', sa.Uuid(), nullable=False),
    sa.Column('selectionne_pour_comparaison', sa.Boolean(), nullable=False),
    sa.Column('ajoute_le', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['poste_id'], ['postes.id'], ),
    sa.ForeignKeyConstraint(['profil_candidat_id'], ['profils_candidats.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recommandations_rejetees',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('profil_candidat_id', sa.Uuid(), nullable=False),
    sa.Column('poste_id', sa.Uuid(), nullable=False),
    sa.Column('rejete_le', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['poste_id'], ['postes.id'], ),
    sa.ForeignKeyConstraint(['profil_candidat_id'], ['profils_candidats.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scores_matching',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('poste_id', sa.Uuid(), nullable=False),
    sa.Column('profil_candidat_id', sa.Uuid(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('classification', sa.Enum('FORTEMENT_RECOMMANDE', 'BON_MATCH', 'A_EXAMINER', name='matchingclassification'), nullable=False),
    sa.Column('version_modele', sa.String(length=50), nullable=False),
    sa.Column('cree_le', sa.DateTime(), nullable=False),
    sa.Column('modifie_le', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['poste_id'], ['postes.id'], ),
    sa.ForeignKeyConstraint(['profil_candidat_id'], ['profils_candidats.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('simulations_entrevue',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('poste_id', sa.Uuid(), nullable=False),
    sa.Column('profil_candidat_id', sa.Uuid(), nullable=False),
    sa.Column('statut', sa.Enum('EN_COURS', 'TERMINEE', 'INTERROMPUE', name='interviewstatus'), nullable=False),
    sa.Column('consentement_donne_le', sa.DateTime(), nullable=True),
    sa.Column('partage_avec_recruteur', sa.Boolean(), nullable=False),
    sa.Column('cree_le', sa.DateTime(), nullable=False),
    sa.Column('modifie_le', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['poste_id'], ['postes.id'], ),
    sa.ForeignKeyConstraint(['profil_candidat_id'], ['profils_candidats.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evenements_pipeline',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('candidature_id', sa.Uuid(), nullable=False),
    sa.Column('etape_origine', sa.Enum('CANDIDATURE', 'SHORTLIST', 'ENTREVUE', 'DECISION', name='pipelinestage'), nullable=True),
    sa.Column('etape_destination', sa.Enum('CANDIDATURE', 'SHORTLIST', 'ENTREVUE', 'DECISION', name='pipelinestage'), nullable=False),
    sa.Column('survenu_le', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['candidature_id'], ['candidatures.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('journaux_matching',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('score_matching_id', sa.Uuid(), nullable=False),
    sa.Column('instantane_entrees', sa.JSON(), nullable=False),
    sa.Column('score_resultat', sa.Integer(), nullable=False),
    sa.Column('explication_resultat', sa.JSON(), nullable=False),
    sa.Column('version_modele', sa.String(length=50), nullable=False),
    sa.Column('cree_le', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['score_matching_id'], ['scores_matching.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('questions_entrevue',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('simulation_id', sa.Uuid(), nullable=False),
    sa.Column('ordre', sa.Integer(), nullable=False),
    sa.Column('texte_question', sa.Text(), nullable=False),
    sa.Column('cree_le', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['simulation_id'], ['simulations_entrevue.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('retours_entrevue',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('simulation_id', sa.Uuid(), nullable=False),
    sa.Column('points_forts', sa.JSON(), nullable=False),
    sa.Column('axes_amelioration', sa.JSON(), nullable=False),
    sa.Column('cree_le', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['simulation_id'], ['simulations_entrevue.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('simulation_id')
    )
    op.create_table('reponses_entrevue',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('question_id', sa.Uuid(), nullable=False),
    sa.Column('texte_reponse', sa.Text(), nullable=False),
    sa.Column('texte_relance', sa.Text(), nullable=True),
    sa.Column('repondu_le', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions_entrevue.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reponses_entrevue')
    op.drop_table('retours_entrevue')
    op.drop_table('questions_entrevue')
    op.drop_table('journaux_matching')
    op.drop_table('evenements_pipeline')
    op.drop_table('simulations_entrevue')
    op.drop_table('scores_matching')
    op.drop_table('recommandations_rejetees')
    op.drop_table('entrees_shortlist')
    op.drop_table('cvs')
    op.drop_table('criteres_poste')
    op.drop_table('competences_candidat')
    op.drop_table('candidatures')
    op.drop_table('profils_candidats')
    op.drop_table('preferences_notification')
    op.drop_index(op.f('ix_postes_jeton_lien_candidature'), table_name='postes')
    op.drop_table('postes')
    op.drop_table('notifications')
    op.drop_table('journaux_email')
    op.drop_index(op.f('ix_jetons_reinitialisation_mot_de_passe_jeton'), table_name='jetons_reinitialisation_mot_de_passe')
    op.drop_table('jetons_reinitialisation_mot_de_passe')
    op.drop_index(op.f('ix_utilisateurs_email'), table_name='utilisateurs')
    op.drop_table('utilisateurs')
    # ### end Alembic commands ###
