"""ajout localisation et type_poste_recherche sur cv (JA-036, JA-035)

Revision ID: 0afea4c45daa
Revises: e3bc758de5af
Create Date: 2026-09-25 19:27:27.805504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0afea4c45daa'
down_revision: Union[str, Sequence[str], None] = 'e3bc758de5af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cv', sa.Column('localisation', sa.String(length=255), nullable=True))
    op.add_column('cv', sa.Column('type_poste_recherche', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cv', 'type_poste_recherche')
    op.drop_column('cv', 'localisation')
    # ### end Alembic commands ###
