"""ajout contraintes unicite shortlist et candidatures

Revision ID: 3d5cfff1ae0c
Revises: 08d3179755b9
Create Date: 2026-09-19 11:18:48.948987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d5cfff1ae0c'
down_revision: Union[str, Sequence[str], None] = '08d3179755b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_candidature_poste_candidat', 'candidatures', ['poste_id', 'profil_candidat_id'])
    op.create_unique_constraint('uq_shortlist_poste_candidat', 'entrees_shortlist', ['poste_id', 'profil_candidat_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_shortlist_poste_candidat', 'entrees_shortlist', type_='unique')
    op.drop_constraint('uq_candidature_poste_candidat', 'candidatures', type_='unique')
    # ### end Alembic commands ###
