"""JA-018/019 : hierarchisation des criteres d'offre et score de matching pondere

Revision ID: 469b0bed9d77
Revises: 0afea4c45daa
Create Date: 2026-09-25 21:16:47.788825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '469b0bed9d77'
down_revision: Union[str, Sequence[str], None] = '0afea4c45daa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('critere_offre',
    sa.Column('id_critere', sa.Uuid(), nullable=False),
    sa.Column('id_offre', sa.Uuid(), nullable=False),
    sa.Column('libelle', sa.String(length=255), nullable=False),
    sa.Column('niveau', sa.Enum('OBLIGATOIRE', 'IMPORTANT', 'SOUHAITABLE', name='niveaucritere'), nullable=False),
    sa.ForeignKeyConstraint(['id_offre'], ['offre.id_offre'], ),
    sa.PrimaryKeyConstraint('id_critere')
    )
    op.create_index(op.f('ix_critere_offre_id_offre'), 'critere_offre', ['id_offre'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_critere_offre_id_offre'), table_name='critere_offre')
    op.drop_table('critere_offre')
    # ### end Alembic commands ###
