"""create interview simulation tables

Revision ID: 56eb17b382b9
Revises: d9659f68d88d
Create Date: 2026-09-18 09:22:10.396687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56eb17b382b9'
down_revision: Union[str, Sequence[str], None] = 'd9659f68d88d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interview_simulations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('candidate_profile_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('EN_COURS', 'TERMINEE', 'INTERROMPUE', name='interviewstatus'), nullable=False),
    sa.Column('consent_given_at', sa.DateTime(), nullable=True),
    sa.Column('shared_with_recruiter', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_profile_id'], ['candidate_profiles.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interview_feedbacks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('simulation_id', sa.Uuid(), nullable=False),
    sa.Column('strengths', sa.JSON(), nullable=False),
    sa.Column('improvement_areas', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['simulation_id'], ['interview_simulations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('simulation_id')
    )
    op.create_table('interview_questions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('simulation_id', sa.Uuid(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['simulation_id'], ['interview_simulations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interview_answers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('question_id', sa.Uuid(), nullable=False),
    sa.Column('answer_text', sa.Text(), nullable=False),
    sa.Column('follow_up_text', sa.Text(), nullable=True),
    sa.Column('answered_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['interview_questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('interview_answers')
    op.drop_table('interview_questions')
    op.drop_table('interview_feedbacks')
    op.drop_table('interview_simulations')
    # ### end Alembic commands ###
