"""ajouter persona recruteur

Revision ID: 5fb200140435
Revises: 4c8e7a91d2f0
Create Date: 2026-09-28 08:44:14.079897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fb200140435'
down_revision: Union[str, Sequence[str], None] = '4c8e7a91d2f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recruteur', sa.Column('persona', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recruteur', 'persona')
    # ### end Alembic commands ###
