"""create jobs and job_criteria tables

Revision ID: 670818a56e82
Revises: 1772380f0a54
Create Date: 2026-09-18 08:39:42.259616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '670818a56e82'
down_revision: Union[str, Sequence[str], None] = '1772380f0a54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('recruiter_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description_raw', sa.Text(), nullable=True),
    sa.Column('description_generated', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('BROUILLON', 'PUBLIEE', 'DEPUBLIEE', name='jobstatus'), nullable=False),
    sa.Column('creation_mode', sa.Enum('CHAT', 'FORMULAIRE', name='jobcreationmode'), nullable=False),
    sa.Column('application_link_token', sa.String(length=64), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['recruiter_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_application_link_token'), 'jobs', ['application_link_token'], unique=True)
    op.create_table('job_criteria',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('criterion_type', sa.Enum('INTITULE', 'LIEU', 'LANGUE', 'EXPERIENCE', 'COMPETENCE', name='criteriontype'), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.Column('level', sa.Enum('OBLIGATOIRE', 'IMPORTANT', 'SOUHAITABLE', name='criterionlevel'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job_criteria')
    op.drop_index(op.f('ix_jobs_application_link_token'), table_name='jobs')
    op.drop_table('jobs')
    # ### end Alembic commands ###
