"""schema initial : utilisateurs, candidats, recruteurs, cv, offres, resultats

Revision ID: 6c0937de45f5
Revises: 
Create Date: 2026-09-21 20:59:36.559077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6c0937de45f5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entreprise',
    sa.Column('id_entreprise', sa.Uuid(), nullable=False),
    sa.Column('nom_entreprise', sa.String(length=255), nullable=False),
    sa.Column('pays', sa.String(length=100), nullable=False),
    sa.Column('localisation_entreprise', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id_entreprise')
    )
    op.create_table('utilisateur',
    sa.Column('id_utilisateur', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('numero_telephone', sa.String(length=30), nullable=False),
    sa.Column('mot_de_passe', sa.String(length=255), nullable=False),
    sa.Column('nom_prenom', sa.String(length=255), nullable=False),
    sa.Column('type_utilisateur', sa.Enum('CANDIDAT', 'RECRUTEUR', name='typeutilisateur'), nullable=False),
    sa.Column('status', sa.Enum('ACTIF', 'INACTIF', 'EN_ATTENTE', 'SUPPRIME', name='statusutilisateur'), nullable=False),
    sa.Column('date_creation', sa.DateTime(), nullable=False),
    sa.Column('date_modification', sa.DateTime(), nullable=True),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id_utilisateur'),
    sa.UniqueConstraint('numero_telephone')
    )
    op.create_index(op.f('ix_utilisateur_email'), 'utilisateur', ['email'], unique=True)
    op.create_table('candidat',
    sa.Column('id_candidat', sa.Uuid(), nullable=False),
    sa.Column('id_utilisateur', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['id_utilisateur'], ['utilisateur.id_utilisateur'], ),
    sa.PrimaryKeyConstraint('id_candidat'),
    sa.UniqueConstraint('id_utilisateur')
    )
    op.create_table('recruteur',
    sa.Column('id_recruteur', sa.Uuid(), nullable=False),
    sa.Column('id_utilisateur', sa.Uuid(), nullable=False),
    sa.Column('id_entreprise', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['id_entreprise'], ['entreprise.id_entreprise'], ),
    sa.ForeignKeyConstraint(['id_utilisateur'], ['utilisateur.id_utilisateur'], ),
    sa.PrimaryKeyConstraint('id_recruteur'),
    sa.UniqueConstraint('id_utilisateur')
    )
    op.create_table('cv',
    sa.Column('id_cv', sa.Uuid(), nullable=False),
    sa.Column('id_candidat', sa.Uuid(), nullable=False),
    sa.Column('resume_cv', sa.Text(), nullable=True),
    sa.Column('experience', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('education', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('langues', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('domaine_etude', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('competences', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('certifications', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('cv_vector', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.Column('cv_hash', sa.String(length=255), nullable=True),
    sa.Column('entretien', sa.Text(), nullable=True),
    sa.Column('statut_cv', sa.String(length=50), nullable=True),
    sa.Column('url_cv', sa.Text(), nullable=True),
    sa.Column('cv', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=False),
    sa.Column('date_modification', sa.DateTime(), nullable=True),
    sa.Column('interview', sa.Boolean(), nullable=False),
    sa.Column('code_cv', sa.String(length=20), nullable=False),
    sa.Column('commentaires_recruteurs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['id_candidat'], ['candidat.id_candidat'], ),
    sa.PrimaryKeyConstraint('id_cv'),
    sa.UniqueConstraint('code_cv'),
    sa.UniqueConstraint('cv_hash'),
    sa.UniqueConstraint('id_candidat')
    )
    op.create_table('offre',
    sa.Column('id_offre', sa.Uuid(), nullable=False),
    sa.Column('id_recruteur', sa.Uuid(), nullable=False),
    sa.Column('titre_offre', sa.String(length=255), nullable=False),
    sa.Column('description', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('type_contrat', sa.String(length=50), nullable=True),
    sa.Column('revenu', sa.Float(), nullable=True),
    sa.Column('offre_vector', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.Column('entretien', sa.Boolean(), nullable=False),
    sa.Column('date_debut', sa.Date(), nullable=True),
    sa.Column('date_fin', sa.Date(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('resume_offre', sa.Text(), nullable=True),
    sa.Column('date_publication', sa.DateTime(), nullable=False),
    sa.Column('date_modification', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_recruteur'], ['recruteur.id_recruteur'], ),
    sa.PrimaryKeyConstraint('id_offre')
    )
    op.create_table('resultat',
    sa.Column('id_resultat', sa.Uuid(), nullable=False),
    sa.Column('id_offre', sa.Uuid(), nullable=False),
    sa.Column('id_cv', sa.Uuid(), nullable=False),
    sa.Column('score_sim', sa.Float(), nullable=False),
    sa.Column('statut_candidature', sa.String(length=50), nullable=True),
    sa.Column('date_modification', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_cv'], ['cv.id_cv'], ),
    sa.ForeignKeyConstraint(['id_offre'], ['offre.id_offre'], ),
    sa.PrimaryKeyConstraint('id_resultat')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resultat')
    op.drop_table('offre')
    op.drop_table('cv')
    op.drop_table('recruteur')
    op.drop_table('candidat')
    op.drop_index(op.f('ix_utilisateur_email'), table_name='utilisateur')
    op.drop_table('utilisateur')
    op.drop_table('entreprise')
    # ### end Alembic commands ###
