"""create applications and pipeline_events tables

Revision ID: 77edc771ae8a
Revises: b048182daf1c
Create Date: 2026-09-18 09:13:00.776030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77edc771ae8a'
down_revision: Union[str, Sequence[str], None] = 'b048182daf1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('candidate_profile_id', sa.Uuid(), nullable=False),
    sa.Column('current_stage', sa.Enum('CANDIDATURE', 'SHORTLIST', 'ENTREVUE', 'DECISION', name='pipelinestage'), nullable=False),
    sa.Column('applied_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_profile_id'], ['candidate_profiles.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pipeline_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('application_id', sa.Uuid(), nullable=False),
    sa.Column('from_stage', sa.Enum('CANDIDATURE', 'SHORTLIST', 'ENTREVUE', 'DECISION', name='pipelinestage'), nullable=True),
    sa.Column('to_stage', sa.Enum('CANDIDATURE', 'SHORTLIST', 'ENTREVUE', 'DECISION', name='pipelinestage'), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pipeline_events')
    op.drop_table('applications')
    # ### end Alembic commands ###
