"""JA-083 desabonnement notifications email

Revision ID: 7ef701dd6a7d
Revises: b6dfcd3d8491
Create Date: 2026-09-24 09:28:43.326579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ef701dd6a7d'
down_revision: Union[str, Sequence[str], None] = 'b6dfcd3d8491'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('utilisateur', sa.Column('notifications_email', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('utilisateur', 'notifications_email')
    # ### end Alembic commands ###
