"""ajout historique criteres, incidents et tests de biais

Revision ID: a4a79a9be89f
Revises: 3d5cfff1ae0c
Create Date: 2026-09-19 11:36:41.990810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4a79a9be89f'
down_revision: Union[str, Sequence[str], None] = '3d5cfff1ae0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resultats_tests_biais',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('categorie_biais', sa.Enum('GENRE', 'AGE', 'ORIGINE_NOM', 'ETABLISSEMENT', name='biascategory'), nullable=False),
    sa.Column('description_test', sa.Text(), nullable=False),
    sa.Column('ecart_score', sa.Float(), nullable=False),
    sa.Column('version_modele', sa.String(length=50), nullable=False),
    sa.Column('execute_le', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('incidents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('titre', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('criticite', sa.Enum('FAIBLE', 'MOYEN', 'ELEVE', 'CRITIQUE', name='incidentcriticality'), nullable=False),
    sa.Column('statut', sa.Enum('OUVERT', 'EN_COURS', 'RESOLU', 'FERME', name='incidentstatus'), nullable=False),
    sa.Column('signale_par', sa.Uuid(), nullable=True),
    sa.Column('signale_le', sa.DateTime(), nullable=False),
    sa.Column('resolu_le', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['signale_par'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('historique_criteres_poste',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('poste_id', sa.Uuid(), nullable=False),
    sa.Column('critere_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.Enum('AJOUT', 'MODIFICATION', 'SUPPRESSION', name='historyaction'), nullable=False),
    sa.Column('type_critere', sa.String(length=50), nullable=False),
    sa.Column('valeur', sa.String(length=255), nullable=False),
    sa.Column('niveau', sa.String(length=50), nullable=False),
    sa.Column('modifie_par', sa.Uuid(), nullable=False),
    sa.Column('modifie_le', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['critere_id'], ['criteres_poste.id'], ),
    sa.ForeignKeyConstraint(['modifie_par'], ['utilisateurs.id'], ),
    sa.ForeignKeyConstraint(['poste_id'], ['postes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('historique_criteres_poste')
    op.drop_table('incidents')
    op.drop_table('resultats_tests_biais')
    # ### end Alembic commands ###
