"""correction enum RECRUTEUR et consentement Loi 25 (JA-009)

Revision ID: b6dfcd3d8491
Revises: 6c0937de45f5
Create Date: 2026-09-23 20:12:02.479019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6dfcd3d8491'
down_revision: Union[str, Sequence[str], None] = '6c0937de45f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Ajout de la valeur RECRUTEUR à l'enum PostgreSQL existant.
    # Non détecté par l'autogenerate d'Alembic, ajouté manuellement.
    op.execute("ALTER TYPE typeutilisateur ADD VALUE IF NOT EXISTS 'RECRUTEUR'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('utilisateur', sa.Column('consentement_accepte', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('utilisateur', sa.Column('consentement_date', sa.DateTime(), nullable=True))
    op.add_column('utilisateur', sa.Column('consentement_version', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('utilisateur', 'consentement_version')
    op.drop_column('utilisateur', 'consentement_date')
    op.drop_column('utilisateur', 'consentement_accepte')
    # ### end Alembic commands ###

    # Note : PostgreSQL ne permet pas de retirer une valeur d'un enum existant
    # (ALTER TYPE ... DROP VALUE n'existe pas). Un downgrade complet nécessiterait
    # de recréer le type enum sans RECRUTEUR, ce qui échouerait si des lignes
    # utilisent déjà cette valeur. Laissé tel quel intentionnellement.