"""ajout modeles_poste pour E2 personnalisation par persona

Revision ID: d4ea361d88b9
Revises: a4a79a9be89f
Create Date: 2026-09-19 11:50:47.598430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'd4ea361d88b9'
down_revision: Union[str, Sequence[str], None] = 'a4a79a9be89f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table('modeles_poste',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('titre', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('est_publie', sa.Boolean(), nullable=False),
    sa.Column('cree_par', sa.Uuid(), nullable=False),
    sa.Column('cree_le', sa.DateTime(), nullable=False),
    sa.Column('modifie_le', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cree_par'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('criteres_modele_poste',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('modele_id', sa.Uuid(), nullable=False),
    sa.Column('type_critere', sa.String(length=50), nullable=False),
    sa.Column('valeur', sa.String(length=255), nullable=False),
    sa.Column('niveau', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['modele_id'], ['modeles_poste.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    persona_enum = postgresql.ENUM(
        'PME', 'ENTREPRENEUR', 'RESPONSABLE_RH', 'RECRUTEUR', 'GESTIONNAIRE_SANS_RH',
        name='recruteurpersona', create_type=False
    )

    op.create_table('personas_modele_poste',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('modele_id', sa.Uuid(), nullable=False),
    sa.Column('persona', persona_enum, nullable=False),
    sa.ForeignKeyConstraint(['modele_id'], ['modeles_poste.id'], ),
    sa.PrimaryKeyConstraint('id')
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('personas_modele_poste')
    op.drop_table('criteres_modele_poste')
    op.drop_table('modeles_poste')
    # ### end Alembic commands ###
