"""create notification_preferences and recommendation_dismissals tables

Revision ID: d9659f68d88d
Revises: 77edc771ae8a
Create Date: 2026-09-18 09:18:27.527104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9659f68d88d'
down_revision: Union[str, Sequence[str], None] = '77edc771ae8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_preferences',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('notify_new_recommendation', sa.Boolean(), nullable=False),
    sa.Column('notify_application_received', sa.Boolean(), nullable=False),
    sa.Column('notify_pipeline_stage_change', sa.Boolean(), nullable=False),
    sa.Column('notify_interview_proposed', sa.Boolean(), nullable=False),
    sa.Column('notify_application_rejected', sa.Boolean(), nullable=False),
    sa.Column('notify_weekly_summary', sa.Boolean(), nullable=False),
    sa.Column('notify_profile_reminder', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('recommendation_dismissals',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('candidate_profile_id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('dismissed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_profile_id'], ['candidate_profiles.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recommendation_dismissals')
    op.drop_table('notification_preferences')
    # ### end Alembic commands ###
