"""lien de candidature unique et non devinable par offre (JA-026)

Revision ID: e3bc758de5af
Revises: 889bb7461c96
Create Date: 2026-09-25 12:00:09.794041

"""
import secrets
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3bc758de5af'
down_revision: Union[str, Sequence[str], None] = '889bb7461c96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # 1. Colonne d'abord nullable, pour ne pas casser les offres deja existantes
    op.add_column('offre', sa.Column('lien_token', sa.String(length=64), nullable=True))

    # 2. Backfill : un token unique pour chaque offre existante
    conn = op.get_bind()
    ids = [row[0] for row in conn.execute(sa.text("SELECT id_offre FROM offre"))]
    tokens_utilises: set[str] = set()
    for id_offre in ids:
        token = secrets.token_urlsafe(24)
        while token in tokens_utilises:
            token = secrets.token_urlsafe(24)
        tokens_utilises.add(token)
        conn.execute(
            sa.text("UPDATE offre SET lien_token = :token WHERE id_offre = :id_offre"),
            {"token": token, "id_offre": id_offre},
        )

    # 3. Maintenant que toutes les lignes ont une valeur, on rend la colonne obligatoire
    op.alter_column('offre', 'lien_token', nullable=False)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_offre_lien_token'), 'offre', ['lien_token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_offre_lien_token'), table_name='offre')
    op.drop_column('offre', 'lien_token')
    # ### end Alembic commands ###