"""create candidate_profiles cvs and candidate_skills tables

Revision ID: f7f42efdfdf0
Revises: 670818a56e82
Create Date: 2026-09-18 08:53:51.574496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7f42efdfdf0'
down_revision: Union[str, Sequence[str], None] = '670818a56e82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidate_profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('desired_job_type', sa.String(length=255), nullable=True),
    sa.Column('completeness_rate', sa.Integer(), nullable=False),
    sa.Column('talent_pool_consent_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('candidate_skills',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('candidate_profile_id', sa.Uuid(), nullable=False),
    sa.Column('skill_type', sa.Enum('COMPETENCE', 'LANGUE', 'DOMAINE_EXPERIENCE', 'TYPE_POSTE_COMPATIBLE', name='skilltype'), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.Column('source', sa.Enum('EXTRAIT', 'CORRIGE', name='skillsource'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_profile_id'], ['candidate_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cvs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('candidate_profile_id', sa.Uuid(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_type', sa.String(length=10), nullable=False),
    sa.Column('analysis_status', sa.Enum('EN_ATTENTE', 'TRAITE', 'ECHEC', name='cvanalysisstatus'), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_profile_id'], ['candidate_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cvs')
    op.drop_table('candidate_skills')
    op.drop_table('candidate_profiles')
    # ### end Alembic commands ###
