"""initial schema

Revision ID: 963ceb737713
Revises: 
Create Date: 2026-09-22 15:55:52.924900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = '963ceb737713'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.create_table('entreprise',
    sa.Column('id_entreprise', sa.UUID(), nullable=False),
    sa.Column('nom_entreprise', sa.Text(), nullable=False),
    sa.Column('pays', sa.Text(), nullable=False),
    sa.Column('localisation_entreprise', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id_entreprise')
    )
    op.create_table('utilisateur',
    sa.Column('id_utilisateur', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('numero_telephone', sa.String(), nullable=False),
    sa.Column('mot_de_passe', sa.Text(), nullable=False),
    sa.Column('nom_prenom', sa.String(), nullable=False),
    sa.Column('type_utilisateur', sa.Enum('candidat', 'recruteur', name='minitypeutilisateurenum'), nullable=False),
    sa.Column('status', sa.Enum('actif', 'inactif', 'en_attente', 'supprime', name='ministatusutilisateurenum'), nullable=False),
    sa.Column('date_creation', sa.DateTime(), nullable=False),
    sa.Column('date_modification', sa.DateTime(), nullable=True),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id_utilisateur'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('numero_telephone')
    )
    op.create_table('administrateur',
    sa.Column('id_administrateur', sa.UUID(), nullable=False),
    sa.Column('id_utilisateur', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['id_utilisateur'], ['utilisateur.id_utilisateur'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_administrateur')
    )
    op.create_table('candidat',
    sa.Column('id_candidat', sa.UUID(), nullable=False),
    sa.Column('id_utilisateur', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['id_utilisateur'], ['utilisateur.id_utilisateur'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_candidat')
    )
    op.create_table('recruteur',
    sa.Column('id_recruteur', sa.UUID(), nullable=False),
    sa.Column('id_utilisateur', sa.UUID(), nullable=False),
    sa.Column('id_entreprise', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['id_entreprise'], ['entreprise.id_entreprise'], ),
    sa.ForeignKeyConstraint(['id_utilisateur'], ['utilisateur.id_utilisateur'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_recruteur')
    )
    op.create_table('cv',
    sa.Column('id_cv', sa.UUID(), nullable=False),
    sa.Column('id_candidat', sa.UUID(), nullable=False),
    sa.Column('resume_cv', sa.Text(), nullable=True),
    sa.Column('experience', sa.JSON(), nullable=True),
    sa.Column('education', sa.JSON(), nullable=True),
    sa.Column('langues', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('domaine_etude', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('competences', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('certifications', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('cv_vector', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.Column('cv_hash', sa.String(), nullable=True),
    sa.Column('entretien', sa.Text(), nullable=True),
    sa.Column('statut_cv', sa.String(), nullable=True),
    sa.Column('url_cv', sa.Text(), nullable=True),
    sa.Column('cv', sa.JSON(), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=False),
    sa.Column('date_modification', sa.DateTime(), nullable=True),
    sa.Column('interview', sa.Boolean(), nullable=False),
    sa.Column('code_cv', sa.String(), nullable=True),
    sa.Column('commentaires_recruteurs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['id_candidat'], ['candidat.id_candidat'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_cv'),
    sa.UniqueConstraint('code_cv'),
    sa.UniqueConstraint('cv_hash')
    )
    op.create_table('offre',
    sa.Column('id_offre', sa.UUID(), nullable=False),
    sa.Column('id_recruteur', sa.UUID(), nullable=False),
    sa.Column('titre_offre', sa.String(), nullable=False),
    sa.Column('description', sa.JSON(), nullable=True),
    sa.Column('type_contrat', sa.String(), nullable=True),
    sa.Column('revenu', sa.Float(), nullable=True),
    sa.Column('offre_vector', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.Column('entretien', sa.Boolean(), nullable=True),
    sa.Column('date_debut', sa.Date(), nullable=True),
    sa.Column('date_fin', sa.Date(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('resume_offre', sa.Text(), nullable=True),
    sa.Column('date_publication', sa.DateTime(), nullable=False),
    sa.Column('date_modification', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_recruteur'], ['recruteur.id_recruteur'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_offre')
    )
    op.create_table('resultat',
    sa.Column('id_resultat', sa.UUID(), nullable=False),
    sa.Column('id_offre', sa.UUID(), nullable=False),
    sa.Column('id_cv', sa.UUID(), nullable=True),
    sa.Column('score_sim', sa.Float(), nullable=True),
    sa.Column('statut_candidature', sa.String(), nullable=True),
    sa.Column('date_modification', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_cv'], ['cv.id_cv'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['id_offre'], ['offre.id_offre'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_resultat')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resultat')
    op.drop_table('offre')
    op.drop_table('cv')
    op.drop_table('recruteur')
    op.drop_table('candidat')
    op.drop_table('administrateur')
    op.drop_table('utilisateur')
    op.drop_table('entreprise')
    # ### end Alembic commands ###
