"""add refresh token sessions

Revision ID: b89927597392
Revises: b6a4d9f2c810
Create Date: 2026-09-24 22:28:21.298715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b89927597392'
down_revision: Union[str, None] = 'b6a4d9f2c810'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session_authentification',
    sa.Column('id_session', sa.UUID(), nullable=False),
    sa.Column('id_utilisateur', sa.UUID(), nullable=False),
    sa.Column('refresh_token_hash', sa.String(length=64), nullable=False),
    sa.Column('expire_le', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoque_le', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cree_le', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['id_utilisateur'], ['utilisateur.id_utilisateur'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_session'),
    sa.UniqueConstraint('refresh_token_hash')
    )
    op.create_index(op.f('ix_session_authentification_id_utilisateur'), 'session_authentification', ['id_utilisateur'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_session_authentification_id_utilisateur'), table_name='session_authentification')
    op.drop_table('session_authentification')
    # ### end Alembic commands ###
